app/src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Cette email n\'est pas disponible')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("user")]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $userName = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $createDate = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $biography = null;

    #[ORM\Column]
    // #[Assert\Count(
    //     max: 6,
    //     maxMessage: "Vous ne pouvez pas télécharger plus de {{ limit }} images."
    // )]
    // #[Assert\All(
    //     mimeTypes: ["image/jpeg", "image/png", "image/gif"],
    //     mimeTypesMessage: "Veuillez télécharger un fichier de type image (JPG, PNG, GIF)",
    // )]
    private array $profilPhotos = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $job = null;

    #[ORM\ManyToOne(inversedBy: 'Users')]
    private ?Gender $gender = null;

    #[ORM\Column]
    private array $Orientations = [];

    #[ORM\ManyToMany(targetEntity: Activities::class, mappedBy: 'userActivity')]
    private Collection $activities;

    #[ORM\OneToMany(mappedBy: 'userSender', targetEntity: Messages::class)]
    private Collection $messages;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastLocation = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'user1', targetEntity: Likes::class)]
    private Collection $user1;

    #[ORM\OneToMany(mappedBy: 'user2', targetEntity: Likes::class)]
    private Collection $user2;

    public function __construct()
    {
        $this->createDate = new \DateTimeImmutable();
        $this->activities = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->user1 = new ArrayCollection();
        $this->user2 = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->userName;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUserName(string $userName): self
    {
        $this->userName = $userName;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getAge()
    {
        $date_actuelle = new DateTime();
        $diff = $date_actuelle->diff($this->birthDate);
        return  $diff->y;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->createDate;
    }

    public function setCreateDate(\DateTimeInterface $createDate): self
    {
        $this->createDate = $createDate;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }

    public function getProfilPhotos(): array
    {
        return $this->profilPhotos;
    }

    public function setProfilPhotos(array $profilPhotos): self
    {
        $this->profilPhotos = $profilPhotos;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(?string $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getOrientations(): array
    {
        return $this->Orientations;
    }

    public function setOrientations(array $Orientations): self
    {
        $this->Orientations = $Orientations;

        return $this;
    }

    /**
     * @return Collection<int, Activities>
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activities $activity): self
    {
        if (!$this->activities->contains($activity)) {
            $this->activities->add($activity);
            $activity->addUserActivity($this);
        }

        return $this;
    }

    public function removeActivity(Activities $activity): self
    {
        if ($this->activities->removeElement($activity)) {
            $activity->removeUserActivity($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setUserSender($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getUserSender() === $this) {
                $message->setUserSender(null);
            }
        }

        return $this;
    }

    public function getLastLocation(): ?string
    {
        return $this->lastLocation;
    }

    public function setLastLocation(?string $lastLocation): self
    {
        $this->lastLocation = $lastLocation;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function getIsVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Likes>
     */
    public function getUser1(): Collection
    {
        return $this->user1;
    }

    public function addUser1(Likes $user1): self
    {
        if (!$this->user1->contains($user1)) {
            $this->user1->add($user1);
            $user1->setUser1($this);
        }

        return $this;
    }

    public function removeUser1(Likes $user1): self
    {
        if ($this->user1->removeElement($user1)) {
            // set the owning side to null (unless already changed)
            if ($user1->getUser1() === $this) {
                $user1->setUser1(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Likes>
     */
    public function getUser2(): Collection
    {
        return $this->user2;
    }

    public function addUser2(Likes $user2): self
    {
        if (!$this->user2->contains($user2)) {
            $this->user2->add($user2);
            $user2->setUser2($this);
        }

        return $this;
    }

    public function removeUser2(Likes $user2): self
    {
        if ($this->user2->removeElement($user2)) {

app/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Entity\Activities;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

class ProfileController extends AbstractController
{
    #[Route('/profil', name: 'app_profile')]
    public function index(): Response
    {
    
        if($this->getUser() !== null)
        {
            if($this->getUser()->getBiography() == null && empty($this->getUser()->getProfilPhotos()[0]))
            {
                return $this->render('profile/register.html.twig');
            }
            
        }
        else
        {
            return $this->redirectToRoute('app_home');
        }

        return $this->render('profile/index.html.twig');
    }

    #[Route('/profil/addPhoto', name: 'add_photo', methods: 'POST')]
    public function addPhoto(Request $request, ManagerRegistry $doctrine): RedirectResponse
    {
        $entityManager = $doctrine->getManager();
        $user = $this->getUser();

        if (!$user) {
            throw new AccessDeniedHttpException();
        }

        $photo = $request->files->get('photo');
        if (!$photo) {
            return $this->redirectToRoute('app_profile');
        }

        if ($photo) {
            $newFilename = md5(uniqid()).'.'.$photo->guessExtension();
        }
        try {
            $userDir = $this->getParameter("photos_directory"). '/' . $user->getUsername() . $user->getId();

            $photo->move($userDir, $newFilename);

            $userPhotos = $user->getProfilPhotos();
            $userPhotos[] = $newFilename;

            $user->setProfilPhotos($userPhotos);

            $entityManager->persist($user);
            $entityManager->flush();

        } catch (FileException $e) {
            throw new FileException($e);
        }

        return $this->redirectToRoute('app_profile');
    }

    #[Route('/profil/deletePhoto', name: 'delete_photo', methods: 'POST')]
    public function removePhoto(Request $request, ManagerRegistry $doctrine): RedirectResponse
    {
        $entityManager = $doctrine->getManager();
        $user = $this->getUser();

        if (!$user) {
            throw new AccessDeniedHttpException();
        }

        $photoName = $request->request->get('deletePhoto');
        $userDir = $this->getParameter("photos_directory") . '/' . $user->getUsername() . $user->getId();
        $photoPath = $userDir . '/' . $photoName;

        if (file_exists($photoPath)) {
            unlink($photoPath);
        }
        $userPhotos = $user->getProfilPhotos();
        $key = array_search($photoName, $userPhotos);
        if ($key !== false) {
            unset($userPhotos[$key]);
        }
        $user->setProfilPhotos($userPhotos);

        $entityManager->persist($user);
        $entityManager->flush();

        return $this->redirectToRoute('app_profile');
    }

    #[Route('/profil/addMessage', name: 'add_message', methods: 'POST')]
    public function addMessage(Request $request, ManagerRegistry $doctrine): RedirectResponse
    {
        $entityManager = $doctrine->getManager();
        $user = $this->getUser();

        if (!$user) {
            throw new AccessDeniedHttpException();
        }

        $textMessage = $request->request->get('message');

        $user->setBiography($textMessage);

        $entityManager->persist($user);
        $entityManager->flush();
        return $this->redirectToRoute('app_profile');
    }

    #[Route('/profil/addJob', name: 'add_job', methods: 'POST')]
    public function addJob(Request $request, ManagerRegistry $doctrine): RedirectResponse
    {
        $entityManager = $doctrine->getManager();
        $user = $this->getUser();

        if (!$user) {
            throw new AccessDeniedHttpException();
        }

        $textMessage = $request->request->get('job');
        $user->setJob($textMessage);

        $entityManager->persist($user);
        $entityManager->flush();
        return $this->redirectToRoute('app_profile');
    }

    #[Route('/profil/addCity', name: 'add_city', methods: 'POST')]
    public function addCity(Request $request, ManagerRegistry $doctrine): RedirectResponse
    {
        $entityManager = $doctrine->getManager();
        $user = $this->getUser();

        if (!$user) {
            throw new AccessDeniedHttpException();
        }

        $textMessage = $request->request->get('city');

        $user->setCity($textMessage);

        $entityManager->persist($user);
        $entityManager->flush();
        return $this->redirectToRoute('app_profile');
    }

    #[Route('/api/v1/getActivities', name: 'api_activities', methods: 'GET')]
    public function getActivites(EntityManagerInterface $entityManager)
    {
        $activities = $entityManager->getRepository(Activities::class)->findAll();
        
        $encoders = [new JsonEncoder()]; // If no need for XmlEncoder
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        
        // Serialize your object in Json
        $jsonObject = $serializer->serialize($activities, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object;
            }
        ]);
        
        // For instance, return a Response with encoded Json
        return new Response($jsonObject, 200, ['Content-Type' => 'application/json']);
    }

    #[Route('/api/v1/addActivities', name: 'api_activities_add', methods: 'POST')]
    public function addActivites(Request $request, EntityManagerInterface $entityManager)
    {
        $id = $this->getUser()->getId();
        $user = $entityManager->getRepository(Users::class)->find($id);
        $response = new Response;
        $datas = $request->request;

        if($datas == null)
        {
            return $response->setStatusCode(Response::HTTP_NOT_ACCEPTABLE);
        }
        else
        {
            $activities = $entityManager->getRepository(Activities::class)->find($datas->get('id'));
            
            $user->addActivity($activities);

            $entityManager->flush();

            return $response->setStatusCode(Response::HTTP_OK);
        }

        return $response->setStatusCode(Response::HTTP_OK);

    }
}

app/templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{app.user.userName}}{% endblock %}

{% block body %}

<section class="bg-pink-900 h-full p-8">
    <div class="w-full bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 p-6">
        <h2 class="text-4xl font-extrabold dark:text-white">
            {% set username = app.user.userName|lower %}
            {{ username|capitalize }}
        </h2>
        <div class="flex justify-end">
            <a href="{{ logout_url() }}" class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 absolute top-14 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
                Déconnexion
            </a>
        </div>
        <h3> {{app.user.age}} ans </h3>
        <div class="grid grid-cols-2 md:grid-cols-3 gap-4 mb-2">
            {% for photo in app.user.profilPhotos %}
                <div class="relative">
                    <img class="h-auto max-w-full rounded-lg bg-white" src="/photos/{{ app.user.userName }}{{ app.user.id }}/{{ photo }}" alt="">
                    {% if app.user.profilPhotos|length > 1 %}
                        <form class="absolute bottom-1 right-1" method="post" action="{{ path('delete_photo') }}">
                            <input type="hidden" name="deletePhoto" value="{{ photo }}">
                            <button type="submit" class="bg-red-700 text-white px-4 py-2 rounded-md">delete</button>
                        </form>
                    {% endif %}
                </div>
            {% endfor %}

        </div>
        {% if app.user.profilPhotos|length <= 5  %}
            <div class="mb-2" >
                <label class="block mb-1 pr-2 text-sm font-medium text-gray-900 dark:text-white" for="file_input">Ajoute une photo</label>
                <form  class="flex flex-row justify-between" method="post" action="{{ path('add_photo') }}" enctype="multipart/form-data">
                    <input class="block w-full mr-2 text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" type="file" name="photo" required>
                    <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 mt-2 sm:mt-0" type="submit" >Envoyer</button>
                </form>
            </div>
        {% endif %}

        <form method="post" action="{{ path('add_message') }}">
            <div class="w-full mb-2 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-700 dark:border-gray-600">
                <div class="px-4 py-2 bg-white rounded-t-lg dark:bg-gray-800">
                    <label for="comment" class="sr-only">Your comment</label>
                    <textarea id="comment" rows="4" class="w-full px-0 text-sm text-gray-900 bg-white border-0 dark:bg-gray-800 focus:ring-0 dark:text-white dark:placeholder-gray-400" placeholder="Write a comment..." name="message">{% if app.user.biography %}{{ app.user.biography }}{% endif %}</textarea>
                </div>
                <div class="flex items-center justify-between px-3 py-2 border-t dark:border-gray-600">
                    <button type="submit" class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">
                        Post comment
                    </button>
                </div>
            </div>
        </form>
        <form method="post" action="{{ path('add_job') }}" class="mb-2">
            <label for="job" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
            <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    Quel est votre metier ?
                </div>
                <input type="text" name="job" id="job" class="block w-full p-4 pl-[180px] text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search" {% if app.user.job %}value="{{ app.user.job }}"{% endif %} required>
                <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Ajouter</button>
            </div>
        </form>
        <form method="post" action="{{ path('add_city') }}" class="mb-2">
            <label for="city" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
            <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    Quel est votre ville ?
                </div>
                <input type="text" name="city" id="city" class="block w-full p-4 pl-[180px] text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search" {% if app.user.job %}value="{{ app.user.city }}"{% endif %} required>
                <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Ajouter</button>
            </div>
        </form>
        <div class="relative">
            <div id='activities'></div>
            <h2 class="mb-2 text-lg font-semibold text-gray-900 dark:text-white">Vos activitées préférée : </h2>
            <ul class="max-w-md space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
                {% if app.user.activities[0] is defined  %}
                    {% for activity in app.user.activities %}
                        <li>{{activity.name}}</li>
                    {% endfor %}
                {% else %}
                <p>Pas d'activité séléctionné</p>
                {% endif %}
            </ul>
        </div>
    </div>
</section>

{% endblock %}

app/templates/profile/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{app.user.userName}}{% endblock %}

{% block body %}

<div id="app"></div>

{% endblock %}